  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    driverClassName: oracle.jdbc.driver.OracleDriver
    username: eci2


  jpa:
    database: oracle
    generate-ddl: false
    hibernate.ddl-auto: create
    open-in-view: false
    show-sql: true

  upload:
    image:
      location: C:\Users\DONGYUN\Desktop\spring\server3\localmedia
    file:
      location: C:\Users\DONGYUN\Desktop\spring\server3\filemedia

