  datasource:
    url: jdbc:h2:mem:testdb;Mode=Oracle
    driverClassName: oracle.jdbc.driver.OracleDriver
    username: eci2
    password: Ecieci0321

  jpa:
    database: oracle
    generate-ddl: false
    hibernate.ddl-auto: update
    open-in-view: false
    show-sql: true

    properties:
      hibernate:
          dialect: org.hibernate.dialect.H2Dialect

