server:
  port: 8181

spring:
  profiles:
#    active: prod
    include: secret

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    driverClassName: oracle.jdbc.driver.OracleDriver
    username: eci3
    password: Ecieci0321

  jpa:
    database: oracle
    generate-ddl: false
    hibernate.ddl-auto: update
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect


    properties:
      hibernate:
        dialect : org.hibernate.dialect.Oracle10gDialect

    # prod : postman
    # local : test

  # 파일 업로드 크기 설정

  servlet.multipart.max-file-size: 5MB
  servlet.multipart.max-request-size: 5MB


upload:
   image:
     location: C:/Users/DONGYUN/Desktop/spring/server3/prodmedia/image/
#  upload:
#    image:
#      location: local-location
