whitelist:
  main: http://localhost:300
#  local: http://localhost:300
#  chans: https://6a3e-118-36-38-193.ngrok.io

server:
  port: 8081
#  ssl:
#    key-store: classpath:ecikey.p12
#    key-store-type: PKCS12
#    key-store-password: eciserver
#    key-alias: ecikey

spring:
  jackson:
    serialization:
      fail-on-empty-beans: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false

  main:
    allow-bean-definition-overriding: true

  profiles:
    active:
    include: secret

  security.headers.frame: false

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    driverClassName: oracle.jdbc.driver.OracleDriver
    username: eci3
    password: Ecieci0321

  jpa:
    database: oracle
    generate-ddl: false
    hibernate.ddl-auto: update
    open-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.Oracle10gDialect


    properties:
      hibernate:
        dialect : org.hibernate.dialect.Oracle10gDialect

    # prod : postman
    # local : test

  # 파일 업로드 크기 설정

  servlet.multipart.max-file-size: 500MB
  servlet.multipart.max-request-size: 500MB

upload:
#  location
#  #C:/Users/DONGYUN/Desktop/spring/server3/prodmedia/image/
   image:
     location: src/main/prodmedia/image/
   design-info:
     location: src/main/prodmedia/attach-info/
   design-attach:
     location: src/main/prodmedia/design-attach/

#  upload:
#    image:
#      location: prod-location
      # test : local-location
      # prod : prod-location

