server:
  port: 8181

spring:
  profiles:
<<<<<<< HEAD
    active: test
    include: secret
=======
    active: prod
    include: secret

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    driverClassName: oracle.jdbc.driver.OracleDriver
    username: eci2
    password: Ecieci0321

  jpa:
    database: oracle
    generate-ddl: false
    hibernate.ddl-auto: update
    open-in-view: false
    show-sql: true

    properties:
      hibernate:
        dialect : org.hibernate.dialect.Oracle10gDialect

    database-platform : org.hibernate.dialect.Oracle10gDialect

#  spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle10gDialect
#  spring.jpa.database-platform=org.hibernate.dialect.Oracle10gDialect


>>>>>>> e143a8c189dadeaf9a9cad53c67ea454e93f5b71
